# Generated by Django 6.0.5 on 2026-05-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0002_category_statusmodel_menuresto_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_waitress',
            field=models.BooleanField(default=False),
        ),
    ]
